# See LICENSE file for full copyright and licensing details.

{
    'name': 'Whatsapp Client',
    'version': '16.0.0.1.0',
    'license': 'OPL-1',
    'author': "Alphasoft",
    'sequence': 1,
    'website': 'https://www.alphasoft.co.id/',
    'images':  ['images/main_screenshot.png'],
    'summary': 'This module is used for Whatsapp Client Connection',
    'category': 'Extra Tools',
    'depends': [
        'mail',
        'base_setup',
        'contacts',
        'phone_validation',
    ],
    'external_dependencies': {'python': ['html2text']},
    'data': [
        'security/ir.model.access.csv',
        'data/whatsapp_data.xml',
        'data/whatsapp_mail_message_cron.xml',
        'views/res_partner_view.xml',
        'views/mail_channel.xml',
        'views/mail_message.xml',
        'views/mail_template.xml',
        'views/ir_whatsapp_server.xml',
        'views/menuitem_view.xml',
        'wizard/check_partner_mobile_view.xml',
        'wizard/whatsapp_message_view.xml',
    ],
    'assets': {
        # 'web.assets_frontend': [
        #     #('include', 'aos_whatsapp.assets_public_livechat'),
        #     'aos_whatsapp/static/src/public/main.js',
        #     'aos_whatsapp/static/src/services/*.js',
        #     'aos_whatsapp/static/src/legacy/public_livechat_chatbot.js',
        #     'aos_whatsapp/static/src/legacy/public_livechat.scss',
        #     'aos_whatsapp/static/src/legacy/public_livechat_chatbot.scss',
        #     'mail/static/src/utils/*.js',
        #     'mail/static/src/js/utils.js',
        #     'mail/static/src/component_hooks/*.js',
        #     'mail/static/src/services/messaging_service.js',
        # ],
        'web.assets_backend': [
            # 'aos_whatsapp/static/src/js/colors_reset_button/*',
            # 'aos_whatsapp/static/src/js/aos_whatsapp_chatbot_steps_one2many.js',
            # 'aos_whatsapp/static/src/js/aos_whatsapp_chatbot_script_answers_m2m.js',
            'aos_whatsapp/static/src/components/*/*.js',
            # 'aos_whatsapp/static/src/scss/aos_whatsapp_history.scss',
            # 'aos_whatsapp/static/src/scss/aos_whatsapp_form.scss',
            'aos_whatsapp/static/src/components/*/*.xml',
        ],
        'mail.assets_messaging': [
            'aos_whatsapp/static/src/models/*.js',
        ],
        'web.assets_backend': [
            'aos_whatsapp/static/src/*',
        ],
    },
    'demo': [],
    'test': [],
    'css': [],
    'js': [],
    'price': 0.0,
    'currency': 'EUR',
    'installable': True,
    'application': False,
    'auto_install': False,
}
